/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package no.nav.dagpenger.inntekt

import mu.KotlinLogging
import no.nav.dagpenger.streams.Service
import org.apache.kafka.streams.KafkaStreams
import org.apache.kafka.streams.StreamsBuilder

private val LOGGER = KotlinLogging.logger {}

class MinsteinntektRegel(val env: Environment) : Service() {
    override val SERVICE_APP_ID: String = "dagpenger-regel-minsteinntekt"

    override fun setupStreams(): KafkaStreams {
        LOGGER.info { "Initiating start of $SERVICE_APP_ID" }
        val builder = StreamsBuilder()

        val regelEvent = builder.stream<String, String>(
            "privat-dagpenger-regel-v1" //todo: topic name ??
        )

        regelEvent.mapValues { key, value ->
            // kjør regel
        }.to("privat-dagpenger-regel-v1")

        return KafkaStreams(builder.build(), getConfig())
    }

    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            val datalaster = MinsteinntektRegel(Environment())
            datalaster.start()
        }
    }
}
