apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-regel-minsteinntekt
spec:
  env:
    - name:  KAFKA_BOOTSTRAP_SERVERS
      value: "d26apvl00159.test.local:8443,d26apvl00160.test.local:8443,d26apvl00161.test.local:8443"